# Configuration for connection csv-to-postgres-resale
definition_type: connection
resource_name: "csv-to-postgres-resale"
source_configuration_path: sources/resale_flat_csv/configuration.yaml
destination_configuration_path: destinations/ado_local_db/configuration.yaml

# EDIT THE CONFIGURATION BELOW!
configuration:
  status: active # REQUIRED | string | Allowed values: active, inactive, deprecated
  skip_reset: false # OPTIONAL | boolean | Flag to check if the connection should be reset after a connection update
  namespace_definition: source # OPTIONAL | string | Allowed values: source, destination, customformat
  namespace_format: "${SOURCE_NAMESPACE}" # OPTIONAL | string | Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If "${SOURCE_NAMESPACE}" then behaves like namespaceDefinition = 'source'.
  prefix: "resale" # REQUIRED | Prefix that will be prepended to the name of each stream when it is written to the destination
  resource_requirements: # OPTIONAL | object | Resource requirements to run workers (blank for unbounded allocations)
    cpu_limit: "" # OPTIONAL
    cpu_request: "" # OPTIONAL
    memory_limit: "" # OPTIONAL
    memory_request: "" # OPTIONAL
  schedule_type: basic # OPTIONAL | string | Allowed values: basic, cron, manual
  schedule_data: # OPTIONAL | object
    basic_schedule:
      time_unit: hours # REQUIRED | string | Allowed values: minutes, hours, days, weeks, months
      units: 1 # REQUIRED | integer
    # cron:
    #   cron_time_zone: "UTC" # REQUIRED | string
    #   cron_expression: "* */2 * * * ?" # REQUIRED | string
  # operations:
  ## -------- Uncomment and edit the block below if you want to enable Airbyte normalization --------
  #   - name: "Normalization"
  #     operator_configuration:
  #       normalization:
  #         option: "basic"
  #       operator_type: "normalization"
  ## -------- Uncomment and edit the block below if you want to declare a custom transformation --------
  #   - name: "My dbt transformations" # REQUIRED | string
  #     operator_configuration:
  #       dbt:
  #         dbt_arguments: "run" # REQUIRED | string | Entrypoint arguments for dbt cli to run the project
  #         docker_image: "fishtownanalytics/dbt:0.19.1" # REQUIRED | string | Docker image URL with dbt installed
  #         git_repo_branch: "your-repo-branch-name" # OPTIONAL | string | Git branch name
  #         git_repo_url: "https://github.com/<your git repo>" # REQUIRED | string | Git repository URL of the custom transformation project
  #       operator_type: dbt # REQUIRED | string | Allowed values: dbt, normalization
  sync_catalog: # OPTIONAL | object | 🚨 ONLY edit streams.config, streams.stream should not be edited as schema cannot be changed.
    streams:
      - config:
          alias_name: resale_price_bukit_timah
          cursor_field: []
          destination_sync_mode: append
          primary_key: []
          selected: true
          sync_mode: full_refresh
        stream:
          default_cursor_field: []
          json_schema:
            $schema: http://json-schema.org/draft-07/schema#
            properties:
              Address:
                type:
                  - string
                  - 'null'
              Latitude:
                type:
                  - number
                  - 'null'
              Longtitude:
                type:
                  - number
                  - 'null'
              block:
                type:
                  - number
                  - 'null'
              flat_model:
                type:
                  - string
                  - 'null'
              flat_type:
                type:
                  - string
                  - 'null'
              floor_area_sqm:
                type:
                  - number
                  - 'null'
              lease_commence_date:
                type:
                  - number
                  - 'null'
              month:
                type:
                  - string
                  - 'null'
              remaining_lease:
                type:
                  - string
                  - 'null'
              resale_price:
                type:
                  - number
                  - 'null'
              storey_range:
                type:
                  - string
                  - 'null'
              street_name:
                type:
                  - string
                  - 'null'
              town:
                type:
                  - string
                  - 'null'
            type: object
          name: resale_price_bukit_timah
          source_defined_primary_key: []
          supported_sync_modes:
            - full_refresh
