name: get_coordinates
on:
    schedule:
    - cron: '00 00 1 * *'
    workflow_dispatch:
jobs:
  update_plot:
    name: Update data with lat and long
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token:
            ${{secrets.TOKEN}}
        
      - name: Setup Python
        uses: actions/setup-python@v2
        
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
        
      - name: Run Script and Update Plot
        run: |
          jupyter nbconvert --to script get_coordinates.ipynb
          python get_coordinates.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "vibumy@gmail.com"
          git config --local user.name "Github Actions"
          git init
          git add resale_price.csv
          git commit -m "updates hdb listings with lat and long"
          git push origin master
